---
- hosts: all
  gather_facts: no
  vars_files:
    - ../vault.yml

  tasks:
    - name: Check if service unit nginx is running
      become: true
      systemd:
        name: nginx
        state: started
    - name: Run systemctl status nginx
      become: true
      shell: systemctl status nginx
      register: nginx_status
    - name: Print systemctl status nginx
      debug:
        msg: "{{ nginx_status.stdout_lines }}"
    - name: Check if service unit cdlwebservice is running
      become: true
      systemd:
        name: cdlwebservice
        state: started
    - name: Run systemctl status cdlwebservice
      become: true
      shell: systemctl status cdlwebservice
      register: cdlwebservice_status
    - name: Print systemctl status cdlwebservice
      debug:
        msg: "{{ cdlwebservice_status.stdout_lines }}"
    - name: Check if service unit photonqsquer is running
      become: true
      systemd:
        name: photonqsquer
        state: started
    - name: Run systemctl status photonqsquer
      become: true
      shell: systemctl status photonqsquer
      register: photonqsquer_status
    - name: Print systemctl status photonqsquer
      debug:
        msg: "{{ photonqsquer_status.stdout_lines }}"
